[MOSIP-30425] Update bootstrap.properties
mosip/digital-card-service pull request #131
Opened 2024-11-19 16:06 UTC by VSIVAKALYAN

2024-12-16 13:22 UTC, dhanendra06 approved these changes

2024-12-16 15:31 UTC, ckm007 commented on src/main/resources/bootstrap.properties
>  spring.application.name=digital-card,application,digitalcard-template
can we recheck this?

2025-01-02 11:13 UTC, dhanendra06 requested changes

2025-01-02 11:13 UTC, dhanendra06 commented on src/main/resources/bootstrap.properties
>  spring.application.name=digital-card,application,digitalcard-template
@VSIVAKALYAN please modify the application name to digital-card

2025-01-02 12:13 UTC, ckm007 approved these changes

2025-01-02 12:13 UTC, merged