MOSIP-24827
mosip/digital-card-service pull request #27
Opened 2022-12-05 10:14 UTC by dhanendra06

2022-12-08 16:32 UTC, vishwa-vyom requested changes

2022-12-09 10:21 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/controller/DigitalCardController.java
> +            Map<String, Object> additionalAttribute= new HashMap<>();
taken care

2022-12-09 10:21 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/websub/WebSubSubscriptionHelper.java
> +
removed previously its needed but now its not required

2022-12-09 10:22 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/util/Utility.java
> +    }*/
its not required its handle in below method

2022-12-09 10:22 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/service/impl/PDFCardServiceImpl.java
> +				if(additionalAttribute.containsKey("vidType")){
taken care

2022-12-09 10:45 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/service/impl/DigitalCardServiceImpl.java
> +    public void generateDigitalCard(String credential, String credentialType,String dataShareUrl,String eventId,String transactionId,Map<String,Object> additionalAttribute) {
taken care

2022-12-09 14:37 UTC, vishwa-vyom commented on src/main/java/io/mosip/digitalcard/util/Utility.java
> +    }*/
It is better to do this in the postconstruct, so there is no multiple thread trying to fetch it from config server.

2022-12-09 14:38 UTC, vishwa-vyom commented on src/main/java/io/mosip/digitalcard/service/impl/DigitalCardServiceImpl.java
> +    public void generateDigitalCard(String credential, String credentialType,String dataShareUrl,String eventId,String transactionId,Map<String,Object> additionalAttribute) {
As per the change, you are updating even if you creating there, lets not do that because of the performance reasons.

2022-12-09 15:34 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/service/impl/DigitalCardServiceImpl.java
> +    public void generateDigitalCard(String credential, String credentialType,String dataShareUrl,String eventId,String transactionId,Map<String,Object> additionalAttribute) {
taken care

2022-12-09 15:34 UTC, dhanendra06 commented on src/main/java/io/mosip/digitalcard/util/Utility.java
> +    }*/
taken care

2022-12-09 15:46 UTC, vishwa-vyom approved these changes

2022-12-09 15:46 UTC, merged